### PR TITLE
control.lua - initial cleanup

### PR DESCRIPTION
**Pull request by originalfoo**
Ensure all functions are local scoped for performance, also simplified glob_init(). See commits for additional details.

### CODE REVIEW

**Comment by MagmaMcFry** [comment]
The global streamlining seems rather unnecessary, and the local functions break everything because of missing forward declarations. Please test your commits next time before a pull request. Thanks for making me aware of the local function feature though.

**Comment by originalfoo** [comment]
Ah, must have had the wrong zip in the mods folder while testing - sorry about that :(

**Comment by MagmaMcFry** [comment]
You can have a normal unzipped folder in the mods folder. Works exactly like a zipped folder, but you can put your local git repo in there. Great for rapid testing, especially since you don't need to restart Factorio (only reload a save or restart the map or generate a new map) to test changes in control.lua.

**Comment by originalfoo** [comment]
OMG, you have no idea how much easier my life just got! Thanks for the infos!

**Pull request closed without merging**
