### PR TITLE
Relay combinator

### PR DESCRIPTION
**Pull request by justarandomgeek**
Add a relay combinator to pass signals in/out of factory buildings.

Relay combinators pair with lamps and mirror all signals from a single wire. They prefer the red wire, and will ignore the green wire if both are connected. Signals will be delayed one tick passing through this, as if it were a combinator.

### CODE REVIEW

**Comment by MagmaMcFry** [comment]
I've tried it out, and it seems extremely laggy. Sending 80 signals through 12 ports uses 20ms per tick!

**Comment by justarandomgeek** [comment]
Unfortunately, much like your comment shortly above on items - it's heavy, but there's no better way. I've managed to tighten the copy itself up a little bit (~30-40% improvement), but unfortunately because each signal needs a .index added to it there's no way to remove the loop entirely.

The good news is the slowdown is determined by how many signals you send through, which is why i hadn't noticed it yet - I did most of my testing will small numbers of signals. Maybe I'll clamp it down to only take the first 15 signals per port to see how much that helps...

Edit: limiting bandwidth doesn't help. This is fit for low-density signals or single-frame packets only, it seems. Still better than nothing at all.

**Comment by MagmaMcFry** [comment]
I've reduced update rate and it's sorta okay, check out my relay-combinator branch.

**Comment by justarandomgeek** [comment]
But reducing the update rate makes it nearly useless for 1-tick-pulse based signals, as it is likely to miss the single tick during which the signal is present. Circuits pretty much _have_ to run every tick or pulses are nonfunctional.

Also, one of the fixes you made appears to be similar to one of the changes i made on my branch (copying signals array whole), but is not showing here because you closed the pullreq.

**Comment by justarandomgeek** [comment]
I've also put a [request in the forums for .signals to just have a .index property](https://forums.factorio.com/viewtopic.php?f=6&t=29846), so we can just use it as-is, which would make most of the performance impact just evaporate instantly. I wouldn't count on that happening soon though...

**Comment by justarandomgeek** [comment]
Also, I had used a vanilla lamp (and would have used a vanilla combinator except for the number of signal slots) to keep item/recipe clutter down originally - this also fits nicely with using regular pipes/belts to carry items/liquids through, which was one of the things that made factorissimo nicer (to me) than other surface mods, it has nearly no item-clutter!

**Pull request closed without merging**
