### PR TITLE
Performance updates

### PR DESCRIPTION
**Pull request by msu320**
-added Belt scheduler, which adapts to changes in belt flow. 4-36x less cpu usage per belt, at a 2% loss of peak belt compression.
-pollution checks 3x less (matching the ingame frequency of 1x)
-player enter/exiting factory code now ignores stopped players and finds the door faster by looking for just the roboport entity type.

### CODE REVIEW

**Comment by MagmaMcFry** [comment]
Looks neat, and it does improve performance, however in testing it I found that a) the game crashes due to "**Factorissimo**/control.lua:648: attempt to compare nil with number" each time I place a new belt connection, and b) when I use red belts at full load, only one half of the belt gets transported at full throughput, the other half only occasionally receives one or two items.

**Comment by msu320** [comment]
I put bug fixes for those into the commit.
a) I forgot to re-add 4 variables when the connection was created
b) the maximum tick_delta was set at 300 for some reason on one transport line.
I also decided to flip the numbers for how the tick_delta changes. the belt connection should ramp up from sleep faster, and fall back to sleep slower now.

**Comment by msu320** [comment]
wait- found more bugs- I'm closing until the pull is bug free.

**Comment by msu320** [comment]
fixed the bugs that occured on adding belts.
-belt scheduler starts with tick_delta of 1, then slows down as it adapts to item speed on belts.
-express belts should compress

**Comment by MagmaMcFry** [comment]
I'm doing a huge rewrite right now because of various issues that appeared, and also because I want to encapsulate connection types and provide an API to add custom connection types or override existing ones. So I can't pull this right now, but if all goes well, you should literally be able to just copy-paste all the things in your PR into a custom "belt" connection type which I can then make available as a config option (note that I will also implement simple non-adaptive batching as default behavior, with configurable batch length), or if you like you could technically release it as your own addon mod.

**Comment by MagmaMcFry** [comment]
I released a new version, see if you like the changes and API.

**Comment by msu320** [comment]
(relevant to 1.7) I'd try to make an addon mod, but I noticed some API stuff is needed:

-ability to change the handler for an existing connection.
-some way to prioritize which handler is used besides array position when making a new connection.
-the detection and removal of entries/connection handlers in connection_types added by addon mod's that are removed/toggled in the mod configuration for various reasons: the removed mod's cannot run any code to remove the entries themselves.

the other option would be to integrate it into the existing mod (of course) and add configuration options.

**Comment by MagmaMcFry** [comment]
You can override the handler for an existing connection simply by registering a new handler for that connection type. If you want to ensure that you override a connection type created by a different mod, you can just add an optional dependence on that mod.

If a connection type is missing, any connection entries of that connection type are automatically removed, however the involved entities will not be removed.

Yes, there is an issue with connection priority, however that should never be a problem when no two available connection types use the same entities. Again, just override the default connection instead of adding a new one. Note also that if your mod is removed, the default connection handler will get handed your connection data, so you need to make sure it doesn't break, for example by initializing the default handler's data attributes for it.

I'll redo the connections properly in the next major update, so that this all becomes much less of an issue.

**Pull request closed without merging**
