### PR TITLE
Better buildings

### PR DESCRIPTION
**Pull request by ReverseStateMonad**
So, having seen the issues occurring with dead robots I decided to see if I could come up with a quick fix... things may have gotten out of hand so it isn't quick, but it's a fix.  The graphics could use some work, but I'm definitely not an artist, and I think they're at least serviceable placeholders.  I also made no attempt at writing a migration script, given the complexity of the changes.

-Buildings changed from Roboports to Assemblers
 -- Should fix dead robot bug
 -- Proper pipe connections at connection points
-Directional placement possible (N/S/E/W facings)
 -- Connection points and entry/exit points based on facing
-Automatic building layout generation

Screenshots:
http://steamcommunity.com/sharedfiles/filedetails/?id=787280202
http://steamcommunity.com/sharedfiles/filedetails/?id=788353760

### CODE REVIEW

**Comment by ReverseStateMonad** [comment]
Also, added higher tier buildings with tentative recipes/research.
Medium (12X12), Large (18X18), and Huge (24X24) versions of Factory and Power Plant.
http://steamcommunity.com/sharedfiles/filedetails/?id=789583226

**Comment by ReverseStateMonad** [comment]
Also also, changed saving of items from health value to item labels - this is still preliminary, it works but I need to cover a couple of edge cases (e.g. what if there's no room in inventory for another factory).

Edit - Or not, as robots are broken.

**Comment by Tomirad** [comment]
I have crash on begin game. 

`Error while running event on_put_item(ID 9) __Factorissmo__/control.lua:809 attempt to index field 'placement data' (a nil value)`

error

**Comment by ReverseStateMonad** [comment]
Cleaned up reverted commits properly now.

**Comment by MagmaMcFry** [comment]
Your effort is commendable, yet I must politely decline to pull. As it is now, Factorissimo's current code is simply not flexible enough for the improvements I plan to add, so I am in the process of redesigning and rewriting it from scratch to fix all the things that are wrong with it. In the process I have acquired decent Blender skills, and I will be using those to render my own building designs, varying architectural themes between building tiers. [Here's a preview of tier 1 for your enjoyment.](http://i.imgur.com/hAwGONC.png) So unfortunately I won't be using your factory sprites either.

**Comment by ReverseStateMonad** [comment]
As I said, the sprites I made were just placeholders... I don't see it as unfortunate at all that you've made better ones.  Even if you don't use any of my actual code, can I suggest that you take the switch from roboports to assemblers for underlying entity type (and the accompanying directional placement capability, pipe attachments, & fix for the dead robot issue) under consideration for your rewrite?

**Comment by MagmaMcFry** [comment]
Yes, I'll definitely use a new entity type for the factory buildings. The main entity type will be purely cosmetic, but I'll overlay an invisible electric energy interface so I can let players select the energy buffer, throughput and direction using an ingame GUI. I won't make the factory buildings rotatable, however I will make the port layout more symmetrical so rotation is not necessary. Pipe attachments can be managed by script-placing additional invisible entities.

**Pull request closed without merging**
